# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.3
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: 83883690+HashMapsData2Value@users.noreply.github.com
author_name: HashMapsData2Value
contract_name: leak_swap
preset_name: production
project_name: algorand

